FROM ubuntu

RUN apt-get -y update

apt-get -y upgrade

apt-get install -y software-properties-common telnet dnsutils python3-pip

apt-add-repository --yes --update ppa:ansible/ansible

apt-get -y install ansible

pip3 install 'ansible[azure]'
